@startuml
' https://plantuml.com/sequence-diagram

title 애플 소셜 회원가입 시퀀스
autonumber
actor 유저


유저 -> my_letter: ID 만들기 클릭
my_letter -> EID_UI: EID 팝업 오픈, 회원가입 화면 호출 (/join)

유저 -> EID_UI: 애플 회원가입 클릭
EID_UI -> 애플UI: 애플 로그인 진행
애플UI -> 애플인증서버: 인증요청
애플인증서버 -> 인증서버: https://eid-api.test.io/api/accounts/apple/join\nredirect
activate 인증서버
인증서버 --> EID_UI:  Http Status 301
EID_UI -> 인증서버: id token 중복체크 진행 (/api/accounts/check)
인증서버 -> 인증서버: apple public key 목록\n(https://appleid.apple.com/auth/keys)을 \n 이용하여 id_token 검증 후 회원정보 추출
인증서버 --> EID_UI: id token 리턴, 중복여부 리턴
deactivate 인증서버

alt #ffdddd 중복, 기존회원일 경우
    EID_UI -> EID_UI: 중복화면 호출
    EID_UI -> 유저: 팝업 닫거나, 처음부터 시작
else #eff4fb 중복아닌 경우
    EID_UI -> EID_UI: 기존 EID 약관 페이지 호출 (/terms)
    EID_UI -> 인증서버: 애플 회원가입 진행 + id token값 전송 (/api/accounts)
    activate 인증서버
    인증서버 -> 인증서버: authCode 생성
    인증서버 --> EID_UI: authCode 리턴
    deactivate 인증서버
EID_UI -> my_letter: 팝업종료 + authCode 전달

deactivate EID_UI

my_letter -> 인증서버: /api/accounts/token 로 authCode 전달

activate 인증서버

return accessToken, refreshToken 을 리턴

my_letter -> 서버: /api/user/eid-initialize 로 인증서버에서 받은 accessToken, refreshToken 전달

activate 서버
  서버 -> 인증서버: accessToken, refreshToken 검증요청
  인증서버 --> 서버: eid 리턴
  서버 -> 서버:  accessToken 생성 & 저장
return  accessToken, 유저정보(uuid, nickname 등) 리턴

my_letter -> my_letter:  accessToken 로컬스토리지 저장
my_letter -> 유저: 온보딩 진행 or 홈 화면 진입

end

@enduml